name: cookiecutter_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^8.0.5
  provider: ^6.1.2
  dio: ^5.6.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
          weight: 500        
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          weight: 700        
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
          weight: 900